---
galaxy_info:
  author: os-migrate
  role_name: import_users
  namespace: os_migrate
  description: os-migrate resource
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - 30
  galaxy_tags: ["osmigrate"]
dependencies:
  - role: os_migrate.os_migrate.prelude_dst
