- name: Scan available routers
  os_migrate.os_migrate.os_routers_info:
    filters: "{{ os_migrate_src_filters }}"
    cloud: src
    validate_certs: "{{ os_migrate_src_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_src_client_key | default(omit) }}"
  register: src_routers_info

- name: Create id-name pairs of routers to export
  ansible.builtin.set_fact:
    export_routers_ids_names: "{{ (src_routers_info.openstack_routers
      | json_query('[*].{name: name, id: id}')
        | sort(attribute='id')) }}"

- name: Filter names of routers to export
  ansible.builtin.set_fact:
    export_routers_ids_names: "{{ (export_routers_ids_names
      | os_migrate.os_migrate.stringfilter(export_router_interfaces_filter,
       attribute='name')) }}"

- name: Export router interfaces
  os_migrate.os_migrate.export_router_interfaces:
    cloud: src
    path: "{{ os_migrate_data_dir }}/router_interfaces.yml"
    name: "{{ item['id'] }}"
    validate_certs: "{{ os_migrate_src_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_src_client_key | default(omit) }}"
  loop: "{{ export_routers_ids_names }}"
