- name: Read images resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/images.yml"
  register: read_images

- name: Filter images to import
  ansible.builtin.set_fact:
    filtered_images: "{{ (
      read_images.resources
        | from_yaml
        | os_migrate.os_migrate.stringfilter(os_migrate_images_filter,
                                             attribute='params.name') ) }}"

- name: Import images
  os_migrate.os_migrate.import_image:
    cloud: dst
    data: "{{ item }}"
    blob_path: >-
      {{ os_migrate_image_blobs_dir }}/{{ item['_info']['id'] }}-{{ item['params']['name'] }}
    filters: "{{ os_migrate_dst_filters }}"
    validate_certs: "{{ os_migrate_dst_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_dst_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_dst_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_dst_client_key | default(omit) }}"
  loop: "{{ filtered_images }}"
