- name: Read security_group_rules resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/security_group_rules.yml"
  register: read_security_group_rules

- name: Filter security_group_rules to import
  ansible.builtin.set_fact:
    filtered_security_group_rules: "{{ (
      read_security_group_rules.resources
        | os_migrate.os_migrate.stringfilter(os_migrate_security_groups_filter,
                                             attribute='params.security_group_ref.name') ) }}"

- name: Import security_group_rules
  os_migrate.os_migrate.import_security_group_rule:
    cloud: dst
    data: "{{ item }}"
    filters: "{{ os_migrate_dst_filters }}"
    validate_certs: "{{ os_migrate_dst_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_dst_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_dst_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_dst_client_key | default(omit) }}"
  loop: "{{ filtered_security_group_rules }}"
