- name: Scan available keypairs
  os_migrate.os_migrate.os_keypairs_info:
    cloud: src
    validate_certs: "{{ os_migrate_src_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_src_client_key | default(omit) }}"
  register: src_keypairs_info

- name: Create id-name pairs of keypairs to export
  ansible.builtin.set_fact:
    export_keypairs_ids_names: "{{ (src_keypairs_info.openstack_keypairs
      | json_query('[*].{name: name, id: id}')
        | sort(attribute='id')) }}"

- name: Filter names of keypairs to export
  ansible.builtin.set_fact:
    export_keypairs_ids_names: "{{ (export_keypairs_ids_names
      | os_migrate.os_migrate.stringfilter(os_migrate_keypairs_filter,
       attribute='name')) }}"

- name: Export keypair
  os_migrate.os_migrate.export_keypair:
    cloud: src
    path: "{{ os_migrate_data_dir }}/keypairs.yml"
    name: "{{ item['id'] }}"
    validate_certs: "{{ os_migrate_src_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_src_client_key | default(omit) }}"
  loop: "{{ export_keypairs_ids_names }}"
