- name: Conversion host content tasks
  block:
    - name: Display host os
      ansible.builtin.debug:
        msg: >-
          Conversion Host OS is
          {{ ansible_distribution }} {{ ansible_distribution_version }}

    - name: Running pre content hook
      ansible.builtin.shell: "{{ os_migrate_conversion_host_pre_content_hook }}"
      args:
        executable: /bin/bash
      when: os_migrate_conversion_host_pre_content_hook is string

    - name: Include CentOS tasks
      ansible.builtin.include_tasks: centos.yml
      when: ansible_distribution in ['CentOS']

    - name: Include RHEL tasks
      ansible.builtin.include_tasks: rhel.yml
      when: ansible_distribution in ['RedHat']

    - name: Running post content hook
      ansible.builtin.shell: "{{ os_migrate_conversion_host_post_content_hook }}"
      args:
        executable: /bin/bash
      when: os_migrate_conversion_host_post_content_hook is string
