- name: scan available users
  openstack.cloud.identity_user_info:
    cloud: src
    validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_src_client_key|default(omit) }}"
  register: src_users_info

- name: create id-name pairs of users to export keypairs for
  ansible.builtin.set_fact:
    export_users_ids_names: "{{ (
      src_users_info.users
        | json_query('[*].{name: name, id: id}')
        | sort(attribute='id') ) }}"

- name: filter names of users to export keypairs for
  ansible.builtin.set_fact:
    export_users_ids_names: "{{ (
      export_users_ids_names
        | from_yaml
        | os_migrate.os_migrate.stringfilter(os_migrate_users_filter,
                                             attribute='name') ) }}"

- name: export keypairs of a user
  ansible.builtin.include_tasks: export_single_user_keypairs.yml
  loop: "{{ export_users_ids_names }}"
  loop_control:
    loop_var: export_user
