- name: Scan available flavors
  openstack.cloud.compute_flavor_info:
    cloud: src
    validate_certs: "{{ os_migrate_src_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_src_client_key | default(omit) }}"
  register: src_flavors_info

- name: Create id-name pairs of flavors to export
  ansible.builtin.set_fact:
    export_flavors_ids_names: "{{ (
      src_flavors_info.flavors
        | json_query('[*].{name: name, id: id}')
        | sort(attribute='id') ) }}"

- name: Filter names of flavors to export
  ansible.builtin.set_fact:
    export_flavors_ids_names: "{{ (
      export_flavors_ids_names
        | os_migrate.os_migrate.stringfilter(os_migrate_flavors_filter,
                                             attribute='name') ) }}"

- name: Export flavor
  os_migrate.os_migrate.export_flavor:
    cloud: src
    path: "{{ os_migrate_data_dir }}/flavors.yml"
    name: "{{ item['id'] }}"
    validate_certs: "{{ os_migrate_src_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_src_client_key | default(omit) }}"
  loop: "{{ export_flavors_ids_names }}"
