- name: Read projects resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/projects.yml"
  register: read_projects

- name: Filter projects to import
  ansible.builtin.set_fact:
    filtered_projects: "{{ (read_projects.resources
      | from_yaml
      | os_migrate.os_migrate.stringfilter(os_migrate_projects_filter,
       attribute='params.name')) }}"

- name: Import projects
  os_migrate.os_migrate.import_project:
    cloud: dst
    data: "{{ item }}"
    validate_certs: "{{ os_migrate_dst_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_dst_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_dst_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_dst_client_key | default(omit) }}"
  loop: "{{ filtered_projects }}"
