- name: Scan available subnets
  openstack.cloud.subnets_info:
    filters: "{{ os_migrate_src_filters }}"
    cloud: src
    validate_certs: "{{ os_migrate_src_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_src_client_key | default(omit) }}"
  register: src_subnets_info

- name: Create id-name pairs of subnets to export
  ansible.builtin.set_fact:
    export_subnets_ids_names: "{{ (
      src_subnets_info.subnets
        | json_query('[*].{name: name, id: id}')
        | sort(attribute='id') ) }}"

- name: Filter names of subnets to export
  ansible.builtin.set_fact:
    export_subnets_ids_names: "{{ (
      export_subnets_ids_names
        | from_yaml
        | os_migrate.os_migrate.stringfilter(os_migrate_subnets_filter,
                                             attribute='name') ) }}"

- name: Export subnet
  os_migrate.os_migrate.export_subnet:
    cloud: src
    path: "{{ os_migrate_data_dir }}/subnets.yml"
    name: "{{ item['id'] }}"
    validate_certs: "{{ os_migrate_src_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_src_client_key | default(omit) }}"
  loop: "{{ export_subnets_ids_names }}"
