- name: Reboot conversion host if required
  openstack.cloud.server_action:
    action: reboot_hard
    server: "{{ os_migrate_conversion_host_name }}"
    wait: true
    cloud: "{{ os_migrate_conversion_cloud }}"
    validate_certs: "{{ os_migrate_conversion_validate_certs | default(omit) }}"
    ca_cert: "{{ os_migrate_conversion_ca_cert | default(omit) }}"
    client_cert: "{{ os_migrate_conversion_client_cert | default(omit) }}"
    client_key: "{{ os_migrate_conversion_client_key | default(omit) }}"
