- name: Export detached volumes
  hosts: migrator
  environment:
    OS_BLOCK_STORAGE_DEFAULT_MICROVERSION: "3.59"
    OS_CLIENT_CONFIG_FILE: "{{ os_migrate_clouds_path | default(os_migrate_data_dir ~ '/clouds.yaml') }}"
  roles:
    - os_migrate.os_migrate.export_detached_volumes
