- name: Import security groups
  hosts: migrator
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ os_migrate_clouds_path | default(os_migrate_data_dir ~ '/clouds.yaml') }}"
  roles:
    - os_migrate.os_migrate.import_security_groups
